// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChEEzHGJNCu00i75l9TZH0Vb18-BNfukM',
    appId: '1:178045166210:web:e54700a0b5ee7c49fa4a9b',
    messagingSenderId: '178045166210',
    projectId: 'flutter-hayat',
    authDomain: 'flutter-hayat.firebaseapp.com',
    storageBucket: 'flutter-hayat.appspot.com',
    measurementId: 'G-38YLBVR39X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC34lp3Kd3RyaCbrCHnv4tVsjWhohkjc04',
    appId: '1:178045166210:android:dd08cf9b0f31ababfa4a9b',
    messagingSenderId: '178045166210',
    projectId: 'flutter-hayat',
    storageBucket: 'flutter-hayat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvVaZeQlIOWyMDquOdnDnlbnHbQpLYnXQ',
    appId: '1:178045166210:ios:abb016a3379fd1d2fa4a9b',
    messagingSenderId: '178045166210',
    projectId: 'flutter-hayat',
    storageBucket: 'flutter-hayat.appspot.com',
    iosClientId: '178045166210-pshsvmqges7s3r7d0pc97onjaju33f01.apps.googleusercontent.com',
    iosBundleId: 'com.hayat.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvVaZeQlIOWyMDquOdnDnlbnHbQpLYnXQ',
    appId: '1:178045166210:ios:cb2b5d13322a197afa4a9b',
    messagingSenderId: '178045166210',
    projectId: 'flutter-hayat',
    storageBucket: 'flutter-hayat.appspot.com',
    iosClientId: '178045166210-brsqnudoeppkkg166pd38kjr7kaf2v8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
